<?php
/**
 * Base.php Created by
 * User: fenlon
 * Date: 2021/11/25 17:34
 */
class BaseController extends Yaf\Controller_Abstract {
    public function init()
    {

    }

    protected function display($tpl, array $parameters = null)
    {
        Yaf\Dispatcher::getInstance()->disableView();  // 取消视图自动加载
        parent::display($tpl, $parameters); // TODO: Change the autogenerated stub
    }
}