<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FenLon | 登录</title>

    <!-- 离线 Google 字体: Source Sans Pro -->
    <link rel="stylesheet" href="/css/adminlte3/google.css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/adminlte3/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="/css/adminlte3/icheck-bootstrap.min.css">
    <!-- 主题样式 -->
    <link rel="stylesheet" href="/css/adminlte3/adminlte.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <!-- /.login-logo -->
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="#" class="h1"><b>后台管理系统</b></a>
        </div>
        <div class="card-body">
            <p class="login-box-msg">帐户登录</p>

            <form action="" method="post">
                <div class="input-group mb-3">
                    <input type="email" class="form-control" placeholder="邮箱" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" class="form-control" placeholder="密码" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" name="captcha" class="form-control" autocomplete="off" placeholder="验证码" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-check"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <img id="captcha" src="captcha.html" alt="验证码">
                    <div class="input-group-append">
                        <div id="get-captcha" class="input-group-text">
                            <a style="font-size: 12px;" class="text-red" href="javascript:;">看不清，换一张</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="remember">
                            <label for="remember">
                                记住我
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">登录</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <!-- /.social-auth-links -->

            <p class="mb-1">
                <a href="forgot-password.html">忘记密码</a>
            </p>
            <p class="mb-0">
                <a href="register.html" class="text-center">注册</a>
            </p>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="/js/adminlte3/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/js/adminlte3/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<!--<script src="/js/adminlte3/adminlte.min.js"></script>-->
<script src="/js/form.js"></script>
</body>
</html>
