<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FenLon | 重置密码</title>

    <!-- 离线 Google 字体: Source Sans Pro -->
    <link rel="stylesheet" href="/css/adminlte3/google.css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/adminlte3/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="/css/adminlte3/icheck-bootstrap.min.css">
    <!-- 主题样式 -->
    <link rel="stylesheet" href="/css/adminlte3/adminlte.min.css">
</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="#" class="h1"><b>后台管理系统</b></a>
        </div>
        <div class="card-body">
            <p class="login-box-msg">最后一步，设置你的新密码。</p>
            <form action="recover-password.html" method="post">
                <div class="input-group mb-3">
                    <input check-field="true" name="password" type="password" class="form-control" placeholder="密码">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input check-field="true" name="rePassword" type="password" class="form-control" placeholder="确认密码">
                    <input type="hidden" name="email" value="<?php echo $_email;?>">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary btn-block">修改密码</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mt-3 mb-1">
                <a href="login.html">登录</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="/js/adminlte3/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/js/adminlte3/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/js/form.js"></script>
</body>
</html>
