<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>FenLon | 注册</title>

    <!-- 离线 Google 字体: Source Sans Pro -->
    <link rel="stylesheet" href="/css/adminlte3/google.css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="/css/adminlte3/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="/css/adminlte3/icheck-bootstrap.min.css">
    <!-- 主题样式 -->
    <link rel="stylesheet" href="/css/adminlte3/adminlte.min.css">
</head>
<body class="hold-transition register-page">
<div class="register-box">
    <div class="card card-outline card-primary">
        <div class="card-header text-center">
            <a href="#" class="h1"><b>后台管理系统</b></a>
        </div>
        <div class="card-body">
            <p class="login-box-msg">注册新会员</p>

            <form action="register.html" method="post">
                <div class="input-group mb-3">
                    <input name="username" check-field="true" type="text" class="form-control" placeholder="全名" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input name="email" check-field="true" type="email" class="form-control" placeholder="邮箱" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-envelope"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input name="password" check-field="true" type="password" class="form-control" placeholder="密码" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input name="rePassword" check-field="true" type="password" class="form-control" placeholder="再次输入密码" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <span id="feedback-mark" class="error invalid-feedback">请输入邮箱地址</span>
                </div>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <!--<input type="checkbox" id="agreeTerms" name="terms" value="同意">
                            <label for="agreeTerms">
                                我同意这些<a href="#">条款</a>
                            </label>-->
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">注册</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <a href="login.html" class="text-center">我已经有账号了</a>
        </div>
        <!-- /.form-box -->
    </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="/js/adminlte3/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/js/adminlte3/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<!--<script src="/js/adminlte3/adminlte.min.js"></script>-->
<script src="/js/form.js"></script>
</body>
</html>
