<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>版本</b> 1.1.0
    </div>
    <strong>Copyright &copy; 2021-2051 <a href="https://adminlte.io">FenLon</a>.</strong> 保留所有权利。
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- 控制侧边栏内容在这里 -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/js/adminlte3/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/js/adminlte3/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="/js/adminlte3/adminlte.min.js"></script>
</body>
</html>